- hosts: client
  tasks:
        - name: Update core-site.xml file
          blockinfile:
                path: /etc/hadoop/core-site.xml
                insertafter: "<configuration>"
                block: |
                        <property>
                        <name>fs.default.name</name>
                        <value>hdfs://{{ groups['master'][0] }}:9001</value>
                        </property>

        - name: Updating mapred-site.xml file
          blockinfile:
                path: /etc/hadoop/mapred-site.xml
                insertafter: "<configuration>"
                block: |
                        <property>
                        <name>mapred.job.tracker</name>
                        <value>{{ groups['jobtracker'][0] }}:9002</value>
                        </property>













